### ISSUE TITLE
Some Update proposition

### ISSUE THREAD

**Issue by Xellon-fox** [pierrebarlet/qradar2thehive#2]
Hello !

In a first time thank you for this script.

I've tried to use it and i 've some trouble and found solution to solve the majority of them:

1) line 40 : `last_line = data_file[-1]`
The problem here is about the file , if the file is empty " touch id_file.txt",you will get a "out of range" error , maybe a test function "if empty: last_line=0" ?

2) line 42-47 : 
 ```
if int(last_line) < int(last_id):
        first_new_offense = int(last_line)
        file = open(file_id, "w")
        file.write(last_id)
        file.close()
        diff = int(last_id) - first_new_offense
```

Not a good idea , in my test i've initialised my id_file.txt at 0 , but my Qradar have already some open/close/delete offense and in this case an ""out of range" error apear again.
The probleme is you make a delta between your reference id_file.txt (here 0) and the bigest ID BUT if your Json file give you only 15 offenses and the last offense ID is 88 (beacause some offense can be deleted  because of test or anything else)? Your script will try to put 88 event but your json have only 15 ...boom out of range, so use your reference id_file.txt only to know if you need to upgrade the offenses BUT COUNT the number of offenses in your JSON file because sometime you can have this kind of  trouble.

3) line 49-79:
 ```
 for i in range(0,diff):
            offenseId = int(data[i]['id'])
            offenseDescription = str(data[i]['description'])
            offenseSource = str(data[i]['offense_source'])
            offenseMagnitude = int(data[i]['magnitude'])
            offenseSourceNetwork = str(data[i]['source_network'])
            offenseDestinationNetworks = str(data[i]['destination_networks'])
            offenseEventCount = int(data[i]['event_count'])
            
            #To use the following custom fields you have to create them on The Hive with the same internal reference (offenseId,...) and the same type (number,string...)
            #.add_<type>('<internal reference>', <value>)
            customFields = CustomFieldHelper()\
                .add_number('offenseId', offenseId)\
                .add_number('offenseMagnitude', offenseMagnitude)\
                .add_number('offenseEventCount', offenseEventCount)\
                .add_string('offenseSource', offenseSource)\
                .add_string('offenseSourceNetwork', offenseSourceNetwork)\
                .add_string('offenseDestinationNetworks', offenseDestinationNetworks)\
                .add_string('reasonForClosing', "null")\
                .build()
            
            case = Case(title=offenseDescription,
                tlp=3,
                flag=True,
                tags=['offense', 'qradar'],
                description=offenseDescription,
                tasks=tasks,
                customFields=customFields)
            
            id = None
            response_2 = api.create_case(case)
```

YES ..BUT a little probleme here your script is FIFO and the first offense in your JSON file is the newest so:
the newest offense is the first to be create in the hive COOL BUT the problem is if you create more than one case , the newest offense will be the oldest case create : 
Exemple : 3 offense {A,B,C} , A is the newest
the result will be : case :{C,B,A}. You can easly fix that with : 

```
for j in range(0,diff):
            i=diff-j 
            offenseId = int(data[i]['id'])
            offenseDescription = str(data[i]['description'])
```
            .......
PS: ` range(0,diff) `= `range(diff)`
PPS: normally you can do  `range(0,diff,-1)` for change the order but it dont work and i dont know why :/

4) the LAST i promise butthis one i dont how to fix it  :/ 
Many company use proxy and sometime you need to use thme in your env "export http_proxy= ..." 
BUT if all your station is on a LAN you will have trouble because your computer will always ask to the proxy first 

so you can do this 

```
RequestSession = requests.Session()
RequestSession.trust_env = False

response_1 = RequestSession.get(url,headers=headers,verify=False)
```
BUT for thehive4pi i dont know how to do ... i've read we can do this:

`api = TheHiveApi('<URL_THE_HIVE>', '<THE_HIVE_API_KEY>',proxies={})`
and again it dont work :/ and i dont know why :/ 

actually i delete my proxy's parameters.

Thank you again for your work and i hope this can help you

Greetings,

A random guys from SopraSteria Toulouse FRANCE

**Comment by pierrebarlet** [comment]
Thank you very much for these suggestions for improvements, I'll work on them as soon as possible. It's always interesting to get expert advice.

**Comment by pierrebarlet** [comment]
I finally had some time to work on the script. I have corrected most of the reported errors. 
Thank you again for these recommendations.
