### ISSUE TITLE
0 new offenses problem

### ISSUE THREAD

**Issue by zinint** [pierrebarlet/qradar2thehive#3]
Hello, dear pierrebarlet!

Really sorry to bother you but when you'll have time, can you please help with the following issue - in what way the id_file.txt with QRadar last Offence number should be filled (is it just the case id "4562", or may be "id4562" for example)? I've tried it several times, but the result is always the same - "0 new offenses" . Or perhaps your could share an instruction or URL with examples of some sorts?

BTW via curl all the requests are working fine.

Thanks a lot in advance, best regards, zinint.
![screenshot_2](https://user-images.githubusercontent.com/28983182/52374115-84d71200-2a6d-11e9-93eb-9ecb43dc79f9.jpg)

**Comment by pierrebarlet** [comment]
I updated my script to avoid case errors, trying to leave the file id_file.txt empty. 
Normally the file must update with the penultimate offense ID of the qradar to have at least 1 new offense.

**Comment by pierrebarlet** [comment]
You can also try to change the value in the file by yourself to force the script to create cases.
On your picture i see that the last Offense ID is 7464, you can try to change this ID to 7460 directly in id_file.txt and the script should create 4 new cases on TheHive instance.

**Comment by zinint** [comment]
Hello, dear pierrebarlet!

Thanks a lot for your responce and your help!
