### ISSUE TITLE
Error connection

### ISSUE THREAD

**Issue by robben-ar** [pierrebarlet/qradar2thehive#4]
Good afternoon,
I'm having trouble connecting the thehive with the qradar2thehive.py script.
I miss ssl error, I have no valid certificate since it is auto signed.

**ERROR**

root@debian:~/qradar2thehive#  python3 qradar2thehive.py
From cffi callback <function _verify_callback at 0x7fa0804feb70>:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: module 'lib' has no attribute 'X509_up_ref'
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Can't get offenses, check the configuration.

Thank you very much for the development.-

**Comment by robben-ar** [comment]
Try to import a certifi, urllib3 and certificate but with errors.
The line "response_1" in mode FALSE not work for me.

-----------
...
import certifi
import urllib3

**Add 1 with error:**
url = urllib3.HTTPSConnectionPool('192.168.0.20', port=443, cert_reqs='CERT_NONE')

**Add 2 with error:**
url = urllib3.HTTPSConnectionPool(
        cert_file='/root/qradar2thehive/qradar.pem',
        cert_reqs='CERT_NONE',
        ca_certs='/root/qradar2thehive/ca-qradar.crt',
        key_password='/root/qradar2thehive/qradar.key')
...
-----------

Thanks.-

**Comment by pierrebarlet** [comment]
Did you leave the "verify=false" parameter for response_1 ?
I also have a self-signed certificate on qradar and with this parameter i don't have this error.

**Comment by pierrebarlet** [comment]
You could try 
`pip uninstall pyOpenSSL cryptography`
`sudo pip install pyOpenSSL cryptography`
This should fix the error.

**Comment by robben-ar** [comment]
Thanks for quick answer.
I already have those libraries installed.

---
I put the warnings.filterwarnings in **ALWAYS mode**.
With the FALSE option I get the following error now:

root@debian:~/qradar2thehive# python3 qradar2thehive.py
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Can't get offenses, check the configuration.

---
- **Also comment on the JIRA** part because I do not have any.

- I do not have CORTEX either, **should I comment the lines to skip the validation?**
---


Regards!

**Comment by robben-ar** [comment]
I just tried the script on the same server as the QRADAR but it returns the same error.
I installed what the qradar2thehive requires but not work for me.

yum install python34
pip install requests 
pip install thehive4py

**Comment by pierrebarlet** [comment]
You can try to add this to the script:
`import urllib3`
`urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)`

**Comment by robben-ar** [comment]
The same error is repeated.
I repeated the same process in the qradar2thehive installation on the local QRADAR server but it returns the same error.

root@debian:~/qradar2thehive# python3 qradar2thehive.py
/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Can't get offenses, check the configuration.



Thank you very much for the answers!

**Comment by pierrebarlet** [comment]
Mmm... 
Maybe try to add:
```
import requests
from requests.packages.urllib3.exceptions import InsecureRequestWarning

requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
```
and remove:
```
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```

**Comment by robben-ar** [comment]
Good afternoon Pierre,
It keeps returning error.
I can see the error because I'm setting the variable "warnings.filterwarnings ('always')" but if I do not put this variable it responds "Can not get offenses, check the configuration."

**I do not have firewalls or ACLs in the middle.**

This is my script:

---------------

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import print_function
from __future__ import unicode_literals
import json
import warnings
import json
import time
import uuid
import sys
import time
from thehive4py.api import TheHiveApi
from thehive4py.models import Case, CustomFieldHelper, CaseTask, CaseObservable
from requests.packages.urllib3.exceptions import InsecureRequestWarning
import requests
from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
warnings.filterwarnings('always')

#To use this script correctly please configure the following lines
file_id = "</root/qradar2thehive/test-alert-create.py>"
api = TheHiveApi('http://localhost:9000/', 'XXXXXXXXXXXXXXXXXXXXXX')
#warnings.filterwarnings('always')
url = 'https://192.168.100.100/api/siem/offenses?fields=id%2Cstatus%2Cdescription%2Coffense_type%2Coffense_source%2Cmagnitude%2Csource_network%2Cdestination_networks%2Cassigned_to%2Cstart_time%2Cevent_count'
headers = {'accept': 'application/json', 'SEC': 'XXXXXXXXXXXXXXXXXXXXXXXX', 'Version': '9.0'}

#If you're using a selfsigned certificate on your QRadar instance you have to use "verify=false" parameter:
response_1 = requests.get(url,headers=headers,verify=False)

...
---------------


Regards.-

**Comment by pierrebarlet** [comment]
Try to connect to https://<QRADAR_IP_ADDRESS>/api_doc

You should see the API version:
![2019-03-07 10_28_55-security intelligence api](https://user-images.githubusercontent.com/39312275/53946629-79a2f080-40c4-11e9-9663-03b21f05c830.png)

And you can try to make curl requests:
![2019-03-07 10_34_33-security intelligence api](https://user-images.githubusercontent.com/39312275/53946740-a7883500-40c4-11e9-8f78-a089113dac24.png)

After you can try to execute this curl request from the server you are executing the script and you will know if you can access the QRadar Offenses without problems.

Regards.

**Comment by robben-ar** [comment]
Hi Pierre,
This is the answer to "**Try it out**":

------------------------------
![image](https://user-images.githubusercontent.com/16881807/54053194-47c58300-41c5-11e9-9756-e929a7a85eff.png)
------------------------------

By throwing the CURL from the CLI of THE HIVE, it returns the active offenses:
I put it --insecure to the CURL by the self-signed SSL.

--------------------------
```
root@debian:~/qradar2thehive# curl -vvvv --insecure -s -X GET -u admin -H 'Range: items=0-49' -H 'Version: 9.0' -H 'Accept: application/json' 'https://192.168.100.100/api/siem/offenses'
Enter host password for user 'admin':
*   Trying 192.168.100.100...
* TCP_NODELAY set
* Connected to 192.168.100.100 (192.168.100.100) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=localhost.localdomain
*  start date: Apr 19 14:22:15 2018 GMT
*  expire date: Apr 16 14:22:15 2028 GMT
*  issuer: CN=localhost.localdomain
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* Server auth using Basic with user 'admin'
> GET /api/siem/offenses HTTP/1.1
> Host: 192.168.100.100
> Authorization: Basic YWRtaW46QmFzZTRTZWN3MTA=
> User-Agent: curl/7.52.1
> Range: items=0-49
> Version: 9.0
> Accept: application/json
>
< HTTP/1.1 200 200
< Date: Fri, 08 Mar 2019 20:01:07 GMT
< Server: QRadar
< Set-Cookie: SEC=XXXXXXXXXXXXXXXXXXXXXXXXXXX;Path=/;Secure;HttpOnly;
< Set-Cookie: QRadarCSRF=e270e502-511d-4e9f-a563-fa08e78a5d72; Path=/; Secure
< Set-Cookie: AJAXTimeoutLimit=5; Path=/; Secure
< Set-Cookie: isOpenIdAuth=false; Path=/; Secure
< Set-Cookie: openIDSingleSignoutURLs=; Path=/; Secure
< Set-Cookie: openIDProviderName=jsp.QRadar.OpenIDProvider; Path=/; Secure
< Set-Cookie: inactivityTimeout=0; Path=/; Secure
< Strict-Transport-Security: max-age=31622400; includeSubDomains
< Access-Control-Allow-Origin:
< Cache-Control: no-cache, no-store, must-revalidate
< Pragma: no-cache
< Expires: 0
< Content-Range: items 0-0/1
< Content-Type: application/json;charset=UTF-8
< X-Frame-Options: SAMEORIGIN
< Transfer-Encoding: chunked
<
* Curl_http_done: called premature == 0
* Connection #0 to host 10.168.0.220 left intact
[{"username_count":1,"description":"Multiple Login Failures for the Same User\n containing Root Login Failed\n","rules":[{"id":100056,"type":"CRE_RULE"}],"event_count":18,"flow_count":0,"assigned_to":null,"security_category_count":2,"follow_up":false,"source_address_ids":[20,21],"source_count":2,"inactive":false,"protected":false,"category_count":2,"source_network":"other","destination_networks":["other"],"closing_user":null,"close_time":null,"remote_destination_count":1,"start_time":1551997936784,"last_updated_time":1552074928940,"credibility":3,"magnitude":3,"id":87,"categories":["User Login Failure","Admin Login Failure"],"severity":5,"policy_category_count":0,"device_count":2,"closing_reason_id":null,"offense_type":3,"relevance":1,"domain_id":0,"offense_source":"root","local_destination_address_ids":[],"local_destination_count":0,"status":"OPEN"}]
root@debian:~/qradar2thehive#
```
--------------------------


Regards.-

**Comment by robben-ar** [comment]
Pierre,
I was able to connect today with the QRadar and bring the ofenses 👍 
We generated a certificate in Letsencrypt these days and today it went live.
Now I am configuring the Synapse to close the case and impact the QRadar.


Thank you very much for the help and predisposition,
Regards.-

**Comment by pierrebarlet** [comment]
You're welcome.
